
export const TEXTCONSTANTS={
    REGISTERFORMMOBILE:'شماره موبایل را اینجا وارد کنید' ,
    REGISTERFORMLABELNAME:'نام را اینجا وارد کنید' ,
    REGISTERFORMLABELFAMIL:'نام خانوادگی را اینجا وارد کنید' ,
    REGISTERMOBILESENDCODE:'ارسال کد',
    REGISTERFORMCODE:'شش رقم ارسال شده',
    REGISTERMOBILERESEND:'ارسال مجدد',
    REGISTEREMPTYMOBILE:'شماره موبایل را وارد کنید',
    REGISTEREMPTYVALIDCODE:'کد ارسالی به موبایلتان را وارد کنید',
    REGISTERMOBILEUNVALID:'کد وارد شده صحیح نمی باشد',
    REGISTERMOBILEVALID:'ثبت نام شما با موفقیت انجام شد',
    REGISTERFORMNAME:'نام',
    REGISTERFORMFAMIL:'نام خانوادگی',
    REGISTER_NameFAMIL_SUBMIT:'ثبت وادامه',
    REGISTERMOBILEREQUIRED:' شماره موبایل الزامی می باشد',
    REGISTERFORMNAMEREQUIRED:' نام الزامی می باشد',
    REGISTERFORMFAMILREQUIRED:' نام خانوادگی الزامی می باشد',
    REGISTER_NAMEFAMIL_ERROR:' خطا در ذخیره سازی نام و نام خانوادگی',
};
